language: node_js
node_js:
  - "node"

script: "yarn run coverage && yarn run lint && yarn run compile"

before_install:
  - pip install --user codecov
after_success:
  - codecov --file coverage/lcov.info --disable search